### PR TITLE
Wait for a new pplan properly

### LINKED ISSUE #1592: StMgr.test_tmaster_restart_on_same_address fails
```
12:02:36 [ RUN      ] StMgr.test_tmaster_restart_on_same_address
12:02:36 F1202 20:02:29.366122 43024 stmgr_unittest.cpp:1527] Check failed: regular_stmgr->GetPhysicalPlan()->stmgrs(1).data_port() == common.stmgr_baseport_ + 2 (28501 vs. 28502) 
12:02:36 *** Check failure stack trace: ***
12:02:36     @           0x4be0fa  google::LogMessage::Fail()
12:02:36     @           0x4bffc2  google::LogMessage::SendToLog()
12:02:36     @           0x4bdcdf  google::LogMessage::Flush()
12:02:36     @           0x4c08de  google::LogMessageFatal::~LogMessageFatal()
12:02:36     @           0x424c3c  StMgr_test_tmaster_restart_on_same_address_Test::TestBody()
12:02:36     @           0x5de453  testing::internal::HandleExceptionsInMethodIfSupported<>()
12:02:36     @           0x5d189d  testing::Test::Run()
12:02:36     @           0x5d1934  testing::TestInfo::Run()
12:02:36     @           0x5d1a35  testing::TestCase::Run()
12:02:36     @           0x5d1cad  testing::internal::UnitTestImpl::RunAllTests()
12:02:36     @           0x5d1f8e  testing::UnitTest::Run()
12:02:36     @           0x40970c  main
12:02:36     @     0x7f2a483149f4  __libc_start_main
12:02:36     @           0x40eb41  (unknown)
12:02:36 external/bazel_tools/tools/test/test-setup.sh: line 52: 43024 Aborted                 (core dumped) "$@"
12:02:36 ================================================================================
```

### PR DESCRIPTION
**Pull request by congwang**
In test case StMgr.test_tmaster_restart_on_same_address, currently we wait for 3 seconds for a new pplan to come in and then check for the new pplan. This is broken if we don't receive the new pplan within 3 seconds. So, just wait for the change of the pplan.

This should resolve #1592.

### CODE REVIEW

**Comment by objmagic** [comment]
👍

File: heron/stmgr/tests/cpp/server/stmgr_unittest.cpp [hunk 1]
```diff
@@ -1521,7 +1521,8 @@ TEST(StMgr, test_tmaster_restart_on_same_address) {
   // Note: Here we sleep longer compared to the previous test as we need
   // to tmasterClient could take upto 1 second (specified in test_heron_internals.yaml)
   // to retry connecting to tmaster.
-  sleep(3);
+  while (regular_stmgr->GetPhysicalPlan()->stmgrs(1).data_port() == common.stmgr_baseport_ + 1)
```
Comment (billonahill) [inline heron/stmgr/tests/cpp/server/stmgr_unittest.cpp]: does this have the potential to sleep indefinitely?

Comment (objmagic) [inline heron/stmgr/tests/cpp/server/stmgr_unittest.cpp]: maybe, which I guess will timeout Travis or internal CI

Comment (billonahill) [inline heron/stmgr/tests/cpp/server/stmgr_unittest.cpp]: best to not rely on that and provide a hard limit upon which we give up.

Comment (congwang) [inline heron/stmgr/tests/cpp/server/stmgr_unittest.cpp]: It's hard to define a time here, b/c we never know if the message is lost or just delayed. I think relying on CI is fine, otherwise still have the same failure.

**Comment by kramasamy** [comment]
@congwang - Is this resolved?

**Comment by congwang** [comment]
@kramasamy Waiting for @billonahill's feedback.

File: heron/stmgr/tests/cpp/server/stmgr_unittest.cpp (hunk 1 above)
Comment (billonahill) [inline heron/stmgr/tests/cpp/server/stmgr_unittest.cpp]: It's better to provide a reasonable timeout here for how long the test should wait. The CI timeouts can be an hour or more. We don't want this test to hang for that long and potentially clog what is a resource-limited CI queue.

Comment (congwang) [inline heron/stmgr/tests/cpp/server/stmgr_unittest.cpp]: Can you give a reasonable timeout? As in the current code, 3-second was supposed to be reasonable, but it is not... So I don't know what is a reasonable one.

Comment (billonahill) [inline heron/stmgr/tests/cpp/server/stmgr_unittest.cpp]: 30 seconds? It's hard to tell for sure, since I'm not familiar with the specific of what this test is doing. If you start with 30 seconds and we're still timing out we could increase it, or try to understand why.

Comment (congwang) [inline heron/stmgr/tests/cpp/server/stmgr_unittest.cpp]: Makes sense, it is safer to use a longer timeout.

**Comment by billonahill** [comment]
👍
