### PR TITLE
Fix flaky ShellUtils test --- use `waitFor` and increase timeout

### LINKED ISSUE #1269: Possible flaky test: ShellUtilsTest
`ShellUtilsTest` under `heron/spi/tests/java` is possibly flaky.

### PR DESCRIPTION
**Pull request by objmagic**
resolves #1269

### CODE REVIEW

File: heron/spi/tests/java/com/twitter/heron/spi/utils/ShellUtilsTest.java [hunk 1]
```diff
@@ -125,7 +117,11 @@ public void testGetProcessBuilder() throws IOException {
 
     // Process running normally
     Process p = pb.start();
-    wait(10, TimeUnit.MILLISECONDS);
+    try {
+      p.waitFor(2, TimeUnit.SECONDS);
+    } catch (InterruptedException e) {
```
Comment (billonahill) [inline heron/spi/tests/java/com/twitter/heron/spi/utils/ShellUtilsTest.java]: It would be better to| declare this in the throws clause and not handle it, since it should trigger a test failure.
